name: 
markdown: redcarpet
permalink: /:title
sass:
    style: compressed
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
excerpt_separator: <end excerpt/>
timezone: Europe/London